---
version: "3.8"
services:
  main:
    build:
      context: ./docker/main
      dockerfile: Dockerfile
      args:
        - uid=${UID}
        - gid=${GID}
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/opt/runefoil:ro
      - ${HOME}/.config/pulse/cookie:/tmp/pulse.cookie
      - ${XDG_RUNTIME_DIR}/pulse:/tmp/pulse
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - jagexcache:/data/jagexcache
      - ${DOT_RUNELITE_DIR}:/data/jagexcache/.runelite
    user: "root:root"
    environment:
      - "DISPLAY"
      - PULSE_SERVER=/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse.cookie
    devices:
      - /dev/dri
    networks:
      runenet:
          ipv4_address: 10.222.182.2
    dns:
      - 1.1.1.1
    init: true
    command: ["/usr/bin/supervisord"]
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    command:
      - "--plugin-dir=/opt/runelite-mysql"
      - "--sql_mode=NO_ENGINE_SUBSTITUTION"
    restart: always
    volumes:
      - runelite-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      runenet:
          ipv4_address: 10.222.182.3
  mongodb:
    networks:
      runenet:
          ipv4_address: 10.222.182.4
    image: mongo:3.6
    restart: always    
networks:
  runenet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.182.0/24
volumes:
  # The MySQL data volume
  runelite-mysql-data:

  # The jagex cache data volume
  jagexcache:

  # The .dot-runelite datavolume, overridable
  dot-runelite:
