---
version: "3.8"
services:
  main:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - uid=${UID}
        - gid=${GID}
    volumes:
      - .:/opt/runefoil:ro
      - ${HOME}/.config/pulse/cookie:/tmp/pulse.cookie
      - ${XDG_RUNTIME_DIR}/pulse:/tmp/pulse
    user: "root:root"
    environment:
      - "DISPLAY"
      - PULSE_SERVER=/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse.cookie
    devices:
      - /dev/dri
    init: true
    command: ["/usr/bin/supervisord"]
